### ISSUE TITLE
Can't resolve version

### ISSUE THREAD

**Issue by RohitEdathil** [RatakondalaArun/pub.dev-cd#6]
Did exactly as README said still got this error

```
Unable to resolve action `RatakondalaArun/pub.dev-cd@v1`, unable to find version `v1`
```

Maybe Should have been
```
RatakondalaArun/pub.dev-cd@v1.0
```
Instead of 
```
RatakondalaArun/pub.dev-cd@v1
```
Nice project BTW✨

**Comment by RohitEdathil** [comment]
Update: `@v1` is apparently not the problem.
 Seems like [this](https://github.com/actions/runner/issues/792) is the case.

**Comment by RatakondalaArun** [comment]
I use it for one of the packages like this

```yaml
publish:
    name: 🚀 Publish to pub.dev
    runs-on: ubuntu-latest
    needs: [tests]
    steps:
      - uses: actions/checkout@v2.3.4

      - name: 🔧 Setup Dart SDK
        uses: dart-lang/setup-dart@v1.0

      - name: 🚀Publish
        uses: RatakondalaArun/pub.dev-cd@v1.0.0
        with:
          creditionals: ${{secrets.PUB_CREDITIONALS}}
```

https://github.com/RatakondalaArun/tmdb_api/blob/690623e286826addc2a3b02ab3db91f5cd3bbd54/.github/workflows/cd.yaml#L28-L43
